import { NextResponse } from 'next/server'
import { query } from '@/lib/db'
import { decodeQRCodeFromBuffer, parseStudentData } from '@/app/student-management/utils/qr-decoder'

export async function POST(request) {
  try {
    const formData = await request.formData()
    const qrCodeFile = formData.get('qrCode')

    if (!qrCodeFile) {
      return NextResponse.json(
        { success: false, error: 'QR code file is required' },
        { status: 400 }
      )
    }

    console.log('📷 QR code received:', {
      name: qrCodeFile.name,
      type: qrCodeFile.type,
      size: qrCodeFile.size
    })

    // Convert file to buffer
    const arrayBuffer = await qrCodeFile.arrayBuffer()
    const buffer = Buffer.from(arrayBuffer)

    let studentData;
    try {
      // Step 1: Decode the actual QR code
      console.log('🔍 Attempting to decode QR code...');
      const qrContent = await decodeQRCodeFromBuffer(buffer);
      
      // Step 2: Parse the student data from QR content
      studentData = parseStudentData(qrContent);
      console.log('✅ Successfully decoded student data:', studentData);
      
    } catch (decodeError) {
      console.error('❌ QR decoding failed:', decodeError);
      
      return NextResponse.json(
        { 
          success: false, 
          error: 'Could not read QR code. Please ensure you are uploading a valid student QR code.',
          debug: {
            error: decodeError.message,
            suggestion: 'Make sure the QR code was generated by the school system'
          }
        },
        { status: 400 }
      );
    }

    const studentId = studentData.student_id;
    console.log('🎯 EXTRACTED STUDENT ID FROM ACTUAL QR:', studentId);

    // Step 3: Look up student in database
    try {
      console.log('🔍 Checking database for students...');
      
      const allStudents = await query(
        `SELECT id, student_id, student_name, grade, section, status 
         FROM students 
         LIMIT 10`
      );
      
      console.log('📋 All students in database:', allStudents.map(s => ({
        id: s.id,
        student_id: s.student_id,
        name: s.student_name,
        status: s.status
      })));

      const students = await query(
        `SELECT id, student_id, student_name, grade, section, status 
         FROM students 
         WHERE student_id = ?`,
        [studentId]
      );

      console.log('🔍 Query result for student ID', studentId, ':', students);

      if (students.length === 0) {
        return NextResponse.json(
          { 
            success: false, 
            error: `Student with ID "${studentId}" not found in database`,
            debug: {
              searchedId: studentId,
              availableStudents: allStudents.map(s => s.student_id),
              qrData: studentData
            }
          },
          { status: 404 }
        );
      }

      const student = students[0];

      // Check if student is inactive
      if (student.status === 'INACTIVE' || student.status === 'inactive') {
        return NextResponse.json(
          { 
            success: false, 
            error: 'Student account is inactive',
            debug: {
              studentId: student.student_id,
              studentName: student.student_name,
              status: student.status,
              qrData: studentData
            }
          },
          { status: 403 }
        );
      }

      console.log('✅ QR login successful for student:', student.student_name);

      return NextResponse.json({
        success: true,
        data: {
          studentId: student.student_id,
          studentName: student.student_name,
          grade: student.grade,
          section: student.section,
          role: 'student'
        },
        debug: {
          qrData: studentData,
          studentStatus: student.status,
          decodedFromActualQR: true,
          source: studentData.source
        },
        message: 'QR login successful'
      });

    } catch (dbError) {
      console.error('❌ Database error:', dbError);
      return NextResponse.json(
        { 
          success: false, 
          error: 'Database error during login: ' + dbError.message
        },
        { status: 500 }
      );
    }

  } catch (error) {
    console.error('❌ QR login error:', error);
    return NextResponse.json(
      { 
        success: false, 
        error: 'Failed to process QR code: ' + error.message
      },
      { status: 500 }
    );
  }
}